### ISSUE TITLE
[Question] What is the purpose of this script? Not clear to me. Also will it work for all modern mirc and adiirc versions? Thanks

### ISSUE THREAD

**Issue by roboirc** [SReject/mWebSocket#8]

**Comment by SReject** [comment]
This is an mIRC implementation of an [HTTP WebSocket Client](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API). \[[RFC Standardization](https://tools.ietf.org/html/rfc6455)\]

While wrote for mIRC, it should work on AdiIRC
